FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py app.py
COPY ./src ./src

EXPOSE 5000

VOLUME /app/.env

CMD ["python3", "app.py"]
