services:
  mongodb:
    image: mongo:7.0.13-rc1-jammy
    container_name: mongodb
    # ports:
    #   - "${MONGO_PORT_EXTERNAL}:${MONGO_PORT_INTERNAL}"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  videos-app:
    build:
      context: .
      dockerfile: Dockerfile.micro
    container_name: videos-app
    ports:
      - "${VIDEOS_APP_PORT_EXTERNAL}:${VIDEOS_APP_PORT_INTERNAL}"
    depends_on:
      - mongodb
    volumes:
      - .env:/app/.env
    networks:
      - backend
      - frontend

  nginx:
    image: nginx:alpine
    container_name: videos-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./templates:/usr/share/nginx/html
      - ./static:/usr/share/nginx/html/static
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - videos-app

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
